name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Extract version from tag
      id: version
      run: |
        # Remove 'v' prefix if present and set version
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Run tests
      run: |
        go mod download
        go test -v ./...
        
    - name: Build binary
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o volume-syncer ./cmd/server
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          GIT_COMMIT=${{ github.sha }}
        tags: |
          sharedvolume/volume-syncer:${{ steps.version.outputs.version }}
          sharedvolume/volume-syncer:latest
        labels: |
          org.opencontainers.image.title=Volume Syncer
          org.opencontainers.image.description=A high-performance API server for synchronizing data from various sources
          org.opencontainers.image.version=${{ steps.version.outputs.version }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.licenses=MIT
          
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Changes in this Release
          
          ### Docker Images
          - `sharedvolume/volume-syncer:${{ steps.version.outputs.version }}`
          - `sharedvolume/volume-syncer:latest`
          
          ### Installation
          ```bash
          docker pull sharedvolume/volume-syncer:${{ steps.version.outputs.version }}
          ```
          
          For detailed changelog, see the commit history.
        draft: false
        prerelease: false
